### ISSUE TITLE
HTML check failing due to rendered Span usage

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kots.io#150]
https://github.com/replicatedhq/kots.io/pull/149/checks?check_run_id=550323101#step:6:453

@austinchambers is there a way to disable checking this rule? I really like the HTML linting so far, happy to help look into this but I don't know this tool well.

**Comment by austinchambers** [comment]
This was fixed here https://github.com/replicatedhq/kots.io/pull/152

Htmlproofer was locked in a 3.15.x, allowing for patches and hotfixes. They broke it with a hotfix in 3.15.2 🤦‍♂ . This caused false positives on doctype. 

Fixed by rolling a new action force-locking htmlproofer to 3.15.0. Won't happen again now.
