### ISSUE TITLE
Helm Native Docs for vendors should probably swap "packaging" for "installing"

### ISSUE THREAD

**Issue by grantmiller** [replicatedhq/kots.io#615]
https://github.com/replicatedhq/kots.io/blob/ef80348f50c74c272c7bba8477c3edaa00e5be31/content/vendor/helm/using-native-helm-charts.md?plain=1#L4

**Comment by AmberAlston** [comment]
@replicatedhq/day0 @JustinN-Replicated

**Comment by JustinN-Replicated** [comment]
Discussed this with @replicatedhq/day0 today; Is there more context on the suggest change from "Installing with Native Helm" to "Packaging with Native Helm"? The team went this direction since Helm is actually doing the deploy/install of the resources (vs the old workflow where Replicated is doing it directly on the cluster) so the feedback was that using 'packaging' may be a bit misleading. 
Also going to copy in @replicatedhq/replicated-docs since @jonquil2002 was in our standup for this discussion today as well.

**Comment by jonquil2002** [comment]
The language was changed from "packaging" to "installing", so I'm closing this issue.
